POST /gitlab HTTP/1.1
Host: tg-bot-catch.requestcatcher.com
Connection: close
Connection: close
Content-Length: 3581
Content-Type: application/json
User-Agent: GitLab/14.3.0-pre
X-Gitlab-Event: Merge Request Hook
X-Gitlab-Token: 9zorsUdpmRV2gSpDtML8

{
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "id": 9778012,
    "name": "Avokad 1",
    "username": "yalublypisi",
    "avatar_url": "https://secure.gravatar.com/avatar/cfcb220aae8407eabff0d89f57c37d19?s=80&d=identicon",
    "email": "yalublypisi@gmail.com"
  },
  "project": {
    "id": 29555520,
    "name": "Dummyproj",
    "description": "",
    "web_url": "https://gitlab.com/AlexSkilled/dummyproj",
    "avatar_url": null,
    "git_ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
    "git_http_url": "https://gitlab.com/AlexSkilled/dummyproj.git",
    "namespace": "AlexSkilled",
    "visibility_level": 0,
    "path_with_namespace": "AlexSkilled/dummyproj",
    "default_branch": "master",
    "ci_config_path": "",
    "homepage": "https://gitlab.com/AlexSkilled/dummyproj",
    "url": "git@gitlab.com:AlexSkilled/dummyproj.git",
    "ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
    "http_url": "https://gitlab.com/AlexSkilled/dummyproj.git"
  },
  "object_attributes": {
    "assignee_id": null,
    "author_id": 8344330,
    "created_at": "2021-09-21 06:36:44 UTC",
    "description": "",
    "head_pipeline_id": null,
    "id": 117671392,
    "iid": 1,
    "last_edited_at": null,
    "last_edited_by_id": null,
    "merge_commit_sha": null,
    "merge_error": null,
    "merge_params": {
      "force_remove_source_branch": "1"
    },
    "merge_status": "can_be_merged",
    "merge_user_id": null,
    "merge_when_pipeline_succeeds": false,
    "milestone_id": null,
    "source_branch": "test2",
    "source_project_id": 29555520,
    "state_id": 2,
    "target_branch": "master",
    "target_project_id": 29555520,
    "time_estimate": 0,
    "title": "Test2",
    "updated_at": "2021-09-21 06:41:28 UTC",
    "updated_by_id": null,
    "url": "https://gitlab.com/AlexSkilled/dummyproj/-/merge_requests/1",
    "source": {
      "id": 29555520,
      "name": "Dummyproj",
      "description": "",
      "web_url": "https://gitlab.com/AlexSkilled/dummyproj",
      "avatar_url": null,
      "git_ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "git_http_url": "https://gitlab.com/AlexSkilled/dummyproj.git",
      "namespace": "AlexSkilled",
      "visibility_level": 0,
      "path_with_namespace": "AlexSkilled/dummyproj",
      "default_branch": "master",
      "ci_config_path": "",
      "homepage": "https://gitlab.com/AlexSkilled/dummyproj",
      "url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "http_url": "https://gitlab.com/AlexSkilled/dummyproj.git"
    },
    "target": {
      "id": 29555520,
      "name": "Dummyproj",
      "description": "",
      "web_url": "https://gitlab.com/AlexSkilled/dummyproj",
      "avatar_url": null,
      "git_ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "git_http_url": "https://gitlab.com/AlexSkilled/dummyproj.git",
      "namespace": "AlexSkilled",
      "visibility_level": 0,
      "path_with_namespace": "AlexSkilled/dummyproj",
      "default_branch": "master",
      "ci_config_path": "",
      "homepage": "https://gitlab.com/AlexSkilled/dummyproj",
      "url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "ssh_url": "git@gitlab.com:AlexSkilled/dummyproj.git",
      "http_url": "https://gitlab.com/AlexSkilled/dummyproj.git"
    },
    "last_commit": {
      "id": "e98e0038ab298d7bcd18f095ba41c34fc57d6cd1",
      "message": "Update README.md",
      "title": "Update README.md",
      "timestamp": "2021-08-16T15:04:39+00:00",
      "url": "https://gitlab.com/AlexSkilled/dummyproj/-/commit/e98e0038ab298d7bcd18f095ba41c34fc57d6cd1",
      "author": {
        "name": "alex",
        "email": "olegthander@yandex.ru"
      }
    },
    "work_in_progress": false,
    "total_time_spent": 0,
    "time_change": 0,
    "human_total_time_spent": null,
    "human_time_change": null,
    "human_time_estimate": null,
    "assignee_ids": [],
    "state": "closed",
    "action": "close"
  },
  "labels": [],
  "changes": {
    "state_id": {
      "previous": 1,
      "current": 2
    },
    "updated_at": {
      "previous": "2021-09-21 06:36:44 UTC",
      "current": "2021-09-21 06:41:28 UTC"
    }
  },
  "repository": {
    "name": "Dummyproj",
    "url": "git@gitlab.com:AlexSkilled/dummyproj.git",
    "description": "",
    "homepage": "https://gitlab.com/AlexSkilled/dummyproj"
  }
}