version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - 10010:10010
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gitlab_bot
      POSTGRES_PASSWORD: 9_9
      POSTGRES_DB: gitlab_bot
    ports:
      - "1000:1000"