image: golang:latest

variables:
  REPO_NAME: gitlab.com/skilled/tn-cicd-tg-bot

stages:
  - test
  - build

compile:
  stage: build
  script:
    - cd cmd/tn-cicd-tg-bot
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/mybinary
  artifacts:
    paths:
      - mybinary
