POST /gitlab HTTP/1.1
Host: tg-bot-catch.requestcatcher.com
Connection: close
Connection: close
Content-Length: 1899
Content-Type: application/json
X-Gitlab-Event: Pipeline Hook
X-Gitlab-Token: CsWEX7bHAQAs3kaKHsna

{
  "object_kind": "pipeline",
  "object_attributes": {
    "id": 3164,
    "ref": "telegram",
    "tag": false,
    "sha": "912fe5ae6e9b2420465a484659ebbc06d557850e",
    "before_sha": "171b7066891f0d433942b0c2a6d53a42a319fbc7",
    "source": "push",
    "status": "failed",
    "detailed_status": "failed",
    "stages": [
      "build"
    ],
    "created_at": "2021-06-10T09:13:12.068Z",
    "finished_at": "2021-06-10T09:13:23.136Z",
    "duration": 9,
    "variables": []
  },
  "merge_request": null,
  "user": {
    "name": "Alexanger",
    "username": "AlexBrin",
    "avatar_url": "https://secure.gravatar.com/avatar/d7f213a177efe279b60dab0e7ba6ac44?s=80\u0026d=identicon",
    "email": "g.a.androidjc2@ya.ru"
  },
  "project": {
    "id": 1756,
    "name": "tn-cicd-tg-bot",
    "description": "",
    "web_url": "https://gitlab.ru/skilled/tn-cicd-tg-bot",
    "avatar_url": null,
    "git_ssh_url": "git@gitlab.ru:skilled/tn-cicd-tg-bot.git",
    "git_http_url": "https://gitlab.ru/skilled/tn-cicd-tg-bot.git",
    "namespace": "alex",
    "visibility_level": 0,
    "path_with_namespace": "skilled/tn-cicd-tg-bot",
    "default_branch": "master",
    "ci_config_path": null
  },
  "commit": {
    "id": "912fe5ae6e9b2420465a484659ebbc06d557850e",
    "message": "Промежуточный коммит\n\n",
    "title": "Промежуточный коммит",
    "timestamp": "2021-06-10T12:13:05+03:00",
    "url": "https://gitlab.ru/skilled/tn-cicd-tg-bot/-/commit/912fe5ae6e9b2420465a484659ebbc06d557850e",
    "author": {
      "name": "Alexander",
      "email": "g.a.androidjc2@ya.ru"
    }
  },
  "builds": [
    {
      "id": 8311,
      "stage": "build",
      "name": "compile",
      "status": "failed",
      "created_at": "2021-06-10T09:13:12.102Z",
      "started_at": "2021-06-10T09:13:13.250Z",
      "finished_at": "2021-06-10T09:13:22.837Z",
      "when": "on_success",
      "manual": false,
      "allow_failure": false,
      "user": {
        "name": "Alexanger",
        "username": "AlexBrin",
        "avatar_url": "https://secure.gravatar.com/avatar/d7f213a177efe279b60dab0e7ba6ac44?s=80\u0026d=identicon",
        "email": "g.a.androidjc2@ya.ru"
      },
      "runner": {
        "id": 254,
        "description": "desc",
        "active": true,
        "is_shared": false
      },
      "artifacts_file": {
        "filename": null,
        "size": null
      }
    }
  ]
}