CREATE TABLE IF NOT EXISTS tg_user (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,

    tg_username TEXT,
    tg_chat_id INTEGER,

    CONSTRAINT chat_id UNIQUE (tg_chat_id)
);

CREATE TABLE IF NOT EXISTS gitlab_user (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,

    user_id INTEGER REFERENCES tg_user(id),

    token TEXT,
    base_url TEXT
);