CREATE TABLE IF NOT EXISTS tg_user
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,

    tg_username TEXT
);

CREATE TABLE IF NOT EXISTS gitlab_user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT,

    user_id  INTEGER REFERENCES tg_user (id),

    token    TEXT,
    base_url TEXT
);

CREATE TABLE IF NOT EXISTS project
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    web_url         TEXT,
    repository_name TEXT
);

CREATE TABLE IF NOT EXISTS users_projects
(
    user_id    INTEGER REFERENCES gitlab_user (id),
    project_id INTEGER REFERENCES project (id)
)